server:
  port: 9402
  servlet:
    context-path: /order

spring:
  profiles:
    active: dev

  application:
    name: security-oauth2-order

  cloud:
    nacos:
      discovery:
        server-addr: ENC(YvJQQ0PBN7Rfq5tFdf28nwzaVRdnoA+oZNIN93A/rCg=) #往这个地址注册自己,不指定命名空间。会默认注册到public里面去，不指定会分组，会注册到default分组中去
        username: nacos
        password: ENC(GmCWpPm6LjVVHJOn6SJZXw==)
        namespace: 791aacd4-29c3-4f85-92ab-5606c7cd108b #表示注册到这个命名空间
        service: order  #这个是服务名称，如果不写，默认取应用名称作为服务名称
        group: dev



  redis:
    port: 6379
    host: ENC(/f5DkTNCTuQjfyaISe7BmuOIgB0YjIA5)
    password: ENC(K4io0bLVFL5qzbj+RqzexeVu9IPWLGlH)

jasypt:
  encryptor:
    password: modebing
    algorithm: PBEWithMD5AndDES


management:
  endpoints:
    web:
      exposure:
        include: "*"

