server: 
  port: 56083


spring:
  ##################### DB #####################
  datasource:
    ds0:
      url: jdbc:mysql://47.98.252.249:3306/bank1?useUnicode=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT user()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000


  cloud:
    nacos:
      discovery:
        server-addr: 47.98.252.249:8848 #往这个地址注册自己,不指定命名空间。会默认注册到public里面去，不指定会分组，会注册到default分组中去
        username: nacos
        password: nacos
        namespace: cdb275ef-fb91-449f-8da8-1afcc7123e53
        group: TCC_GROUP

org:
  dromara:
    hmily :
      serializer : kryo
      recoverDelayTime : 30
      retryMax : 30
      scheduledDelay : 30
      scheduledThreadMax :  10
      repositorySupport : db
#      全局事务的发起方，设为true
      started: true
      hmilyDbConfig :
        driverClassName  : com.mysql.jdbc.Driver
        url :  jdbc:mysql://47.98.252.249:3306/hmily?useUnicode=true
        username : root
        password : 123456



logging:
  level:
    root: info
    org.springframework.web: info
    org.apache.ibatis: info
    org.dromara.hmily.bonuspoint: debug
    org.dromara.hmily.lottery: debug
    org.dromara.hmily: debug
    io.netty: info
    cn.itcast.wanxintx.seatademo.bank2: debug


