spring:
  application:
    name: dtx-mq-demo-bank1
  devtools:
    restart:
      enabled: true
      additional-paths:
        - src/main/java
  datasource:
    url: jdbc:mysql://47.98.252.249:3306/bank1?useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT user()
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      min-idle: 5

  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    connection-timeout: 120000
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: MANUAL

  cloud:
    nacos:
      discovery:
        server-addr: 47.98.252.249:8848 #往这个地址注册自己,不指定命名空间。会默认注册到public里面去，不指定会分组，会注册到default分组中去
        username: nacos
        password: nacos
        namespace: 631c5151-bdb8-46fe-b2fa-0704638b0949 #表示注册到这个命名空间
        #        service: nacos-config  #这个是服务名称，如果不写，默认取应用名称作为服务名称
        group: rabbitmq
server:
  port: 56801
  servlet:
    context-path: /bank1


mybatis-plus:
  type-aliases-package: cn.itcast.dtx.txmsgdemo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    cn.itcast.dtx.txmsgdemo.bank1.dao: debug


