server:
  port: 5002



spring:
  application:
    name: rent-car-service


eureka:
  client: # 拉取服务列表到本地
    service-url:
      #      defaultZone: http://eureka-server-001/eureka
      defaultZone: http://eureka7001.com:7001/eureka #指定注册地址

    register-with-eureka: true # 可以不往eureka注册
    fetch-registry: true # 拉取服务列表到本地
    registry-fetch-interval-seconds: 10 # 为了缓解服务列表脏读问题，时间越短 ，脏读越少，但是比较耗性能，就是每隔多久去取服务列表
  instance:
    hostname: localhost #应用名称，最好写主机
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10 #实例续约时间


#feign 只是帮你去封装了远程调用的功能，底层还是ribbon，所以我们要去修改ribbon的超时时间去调整超时时间
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 3000 # 给feign3s的超时时间
  ConnectTimeout: 3000 # 给feign3s的连接服务超时时间

management:
  endpoints:
    web:
      exposure:
        include: '*'
