server:
  port: 9401
  servlet:
    context-path: /auth

spring:
  profiles:
    active: dev

  application:
    name: security-oauth2-auth

  cloud:
    nacos:
      discovery:
        server-addr: ENC(YvJQQ0PBN7Rfq5tFdf28nwzaVRdnoA+oZNIN93A/rCg=) #往这个地址注册自己,不指定命名空间。会默认注册到public里面去，不指定会分组，会注册到default分组中去
        username: nacos
        password: ENC(GmCWpPm6LjVVHJOn6SJZXw==)
        namespace: 791aacd4-29c3-4f85-92ab-5606c7cd108b #表示注册到这个命名空间
        service: auth  #这个是服务名称，如果不写，默认取应用名称作为服务名称
        group: dev


  main:
    allow-bean-definition-overriding: true


  redis:
    port: 6379
    host: ENC(/f5DkTNCTuQjfyaISe7BmuOIgB0YjIA5)
    password: ENC(K4io0bLVFL5qzbj+RqzexeVu9IPWLGlH)
  datasource:
    druid:
      url: ENC(/xi5xR0EX2vNlpt4e3R2rtTrENR73UcsPDJu5OwMXlKwSkibeh02ARBb9dQUIBuLdwoGMh1A6SAcXXXyAiXMcw==)
      username: root
      password: Ju5OwMXlKwSkibeh02ARBb9dQ
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5 # 初始化时建立物理连接的个数
      minIdle: 5 # 最小连接池数量
      maxActive: 20 # 最大连接池数量
      maxWait: 60000 # 获取连接时最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 连接保持空闲而不被驱逐的最小时间
      validationQuery: SELECT user() # 用来检测连接是否有效的sql，要求是一个查询语句
      testWhileIdle: true # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: false       # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      poolPreparedStatements: true
      max-pool-prepared-statement-per-connection-size: 50 # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000 #通过connectProperties属性来打开mergeSql功能 慢SQL记录
      db-type: com.alibaba.druid.pool.DruidDataSource


jasypt:
  encryptor:
    password: modebing
    algorithm: PBEWithMD5AndDES

management:
  endpoints:
    web:
      exposure:
        include: "*"


# 第三方指定登录
auth:
  open_id: admin
  open_secret: 123456
  open_grant_type: password