
server:
  port: 7003

spring:
  application:
    name: eureka-server  # 集群的时候应用名称不能改

eureka:
  server:  #eureka既是客户端又是服务端
#    剔除
    eviction-interval-timer-in-ms: 10000  #服务端每隔多少毫秒执行定期剔除的操作
    renewal-percent-threshold: 0.85 # 续约百分比，如果超过85的应用没有建立续约，那么服务器会开启保护机制，不会剔除任何一个服务
  instance: # 实例的配置
      instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
      hostname: eureka7003.com
      prefer-ip-address: true #服务器上注册的实例显示ip具体信息
      lease-expiration-duration-in-seconds: 5  #服务实例续约的时间间隔

  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka,http://eureka7003.com:7003/eureka #指定注册地址
    register-with-eureka: true # 可以不往eureka注册
    fetch-registry: true # 拉取服务列表到本地
    registry-fetch-interval-seconds: 10 # 为了缓解服务列表脏读问题，时间越短 ，脏读越少，但是比较耗性能，就是每隔多久去取服务列表
management:
  endpoints:
    web:
      exposure:
        include: '*'

